### PR TITLE
fix altitude export to scale by 5

### PR DESCRIPTION
**Pull request by zackham**
see all the examples of altitude like this: https://github.com/ridewithgps/rubyfit/blob/master/ext/rubyfit/fit_example.h#L3402

i have no idea how to test this. helpppp

fixes https://github.com/ridewithgps/ridewithgps/issues/5110

### CODE REVIEW

**Comment by arthurljones** [comment]
LGTM but it feels wrong to approve what's now partially my own work. @kingcu, give it a glance, merge, and deploy a new gem version when you can.

**Comment by zackham** [comment]
multi author PRs are the best.  :hand:

**Comment by qrohlf** [comment]
Do we know what's causing this, or is the scaling factor of 5 coming from trial and error?

Also, why do we add 500m to the elevation?

**Comment by kingcu** [comment]
because garmin

**Comment by zackham** [comment]
fwiw they probably add 500 because it's an unsigned int and no triathlete dives below 500 meters.

**Comment by qrohlf** [comment]
@kingcu @zackham thanks for the explanation. I'm trying to passively absorb what I can about Garmin's weirdness since some of this stuff may be relevant when it's time to do the Connect IQ app.

**Pull request merged**
